<a href="https://colab.research.google.com/github/jrDhiraj/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
range = np.arange(0, 100,10)

range

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.zeros((6,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [ ]:
np.random.rand(5)

array([0.79988238, 0.17358858, 0.82887515, 0.48176805, 0.8524588 ])

In [ ]:
np.random.randint(4)

1

In [ ]:
np.random.randint(10,20, 12)

array([16, 10, 11, 16, 13, 15, 10, 11, 10, 13, 11, 16])

In [ ]:
arr = np.array([[1,2,4,3], [1,4,3,2],[0,7,5,6]])
arr

array([[1, 2, 4, 3],
       [1, 4, 3, 2],
       [0, 7, 5, 6]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.size

12

In [ ]:
arr.max()

np.int64(7)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.min()

np.int64(0)

In [ ]:
arr.sort()

In [ ]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [0, 5, 6, 7]])

In [ ]:
arr.sum()

np.int64(38)

In [ ]:
np.sum(arr, axis=1)

array([10, 10, 18])

In [ ]:
arr.std()

np.float64(2.034425935955617)

In [ ]:
arr.mean()

np.float64(3.1666666666666665)

In [ ]:
arr.argmax()

NameError: name 'arr' is not defined

In [ ]:
import numpy as np
arr = np.arange(1,31).reshape(6,5)

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[2]

array([11, 12, 13, 14, 15])

In [ ]:
arr[2,2]

np.int64(13)

In [ ]:
arr[3: ,3: ]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [ ]:
np.sum(s, axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
np.sum(s, axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
sum = np.sum(s, axis=1)

In [ ]:
sum == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
slice = s[0:3, 0:3]

In [ ]:
slice

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [ ]:
slice.sum()

np.int64(45)

In [ ]:
for i in range(0,9,3):
  for j in range(0,9,3):
    print(s[i:i+3, j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [ ]:
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
data.shape

(5, 3)

In [ ]:
total = data.argmax()

In [ ]:
total


np.int64(8)

In [ ]:
avg  = np.mean(data[:,0])


In [ ]:
AVG

NameError: name 'AVG' is not defined

In [ ]:
avg

np.float64(18.4)

In [ ]:
data[:,1]

array([85, 92, 76, 65, 90])

In [ ]:
data.max()

np.int64(95)

In [ ]:
np.max(data[:,2])

np.int64(95)

In [ ]:
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])
data [data[:, 1] >90]

array([[19, 92, 88]])

In [ ]:
data[:, 1]+5
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
data [data[:, 0] < 19]

array([[20, 90, 85]])

In [ ]:
data[:,1] >= 80
data[:,2] >=80

array([False,  True,  True, False,  True])

In [ ]:
import numpy as np


In [ ]:
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
data[:, 0] <19

array([ True, False,  True,  True, False])