<a href="https://colab.research.google.com/github/jrDhiraj/numpy/blob/main/practiceNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np


In [14]:
array = np.arange(10,50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [15]:
array[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [18]:
ra = np.flip(array)
ra

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [24]:
three_identity = np.arange(9)

In [25]:
three_identity.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
np.random.randint(1)

0

In [31]:
np.random.randint(0,1,5)


array([0, 0, 0, 0, 0])

In [33]:
mm = np.random.randint(1,100,10)

In [34]:
mm

array([76,  7, 60, 20, 80, 55, 61, 59, 99, 98])

In [35]:
mm.min()

np.int64(7)

In [36]:
mm.max()

np.int64(99)

In [37]:
np.max(mm)

np.int64(99)

In [40]:
max_index=mm.argmax()

In [41]:
max_index

np.int64(8)

In [42]:
array = np.arange(30,70)

In [43]:
array

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69])

In [45]:
for i in array:
  if i%2==0:
    print(i)

30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68


In [50]:
new_arr = np.arange(25).reshape(5,5)

In [51]:
new_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
new_arr[new_arr % 2 != 0] = -1

In [57]:
new_arr

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1],
       [10, -1, 12, -1, 14],
       [-1, 16, -1, 18, -1],
       [20, -1, 22, -1, 24]])

In [58]:
new_arr[new_arr % 2 == 0] = 0

In [59]:
new_arr

array([[ 0, -1,  0, -1,  0],
       [-1,  0, -1,  0, -1],
       [ 0, -1,  0, -1,  0],
       [-1,  0, -1,  0, -1],
       [ 0, -1,  0, -1,  0]])

In [68]:
ver_stack = np.vstack(array)

In [69]:
ver_stack

array([[30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64],
       [65],
       [66],
       [67],
       [68],
       [69]])

In [66]:
hor_stack = np.hstack(array)

In [67]:
hor_stack

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69])

In [70]:
new_arr

array([[ 0, -1,  0, -1,  0],
       [-1,  0, -1,  0, -1],
       [ 0, -1,  0, -1,  0],
       [-1,  0, -1,  0, -1],
       [ 0, -1,  0, -1,  0]])

In [73]:
top_row = new_arr[0]
top_row

array([ 0, -1,  0, -1,  0])

In [74]:
buttom_row = new_arr[-1]
buttom_row

array([ 0, -1,  0, -1,  0])

In [77]:
left_col = new_arr[1:-1,0]
left_col

array([-1,  0, -1])

In [78]:
right_col = new_arr[1:-1, -1]
right_col

array([-1,  0, -1])

In [79]:
con_matrix = np.concatenate((top_row, buttom_row, left_col, right_col))

In [81]:
con_matrix.reshape(4,4)


array([[ 0, -1,  0, -1],
       [ 0,  0, -1,  0],
       [-1,  0, -1,  0],
       [-1, -1,  0, -1]])

In [82]:
arr = np.arange(1,17)

In [83]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [84]:
normalized_arr = (arr - arr.min())/(np.max(arr)-np.min(arr))
normalized_arr

array([0.        , 0.06666667, 0.13333333, 0.2       , 0.26666667,
       0.33333333, 0.4       , 0.46666667, 0.53333333, 0.6       ,
       0.66666667, 0.73333333, 0.8       , 0.86666667, 0.93333333,
       1.        ])

In [88]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [92]:
b = np.arange(6,15).reshape(3,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [93]:
result = np.dot(a,b)

In [94]:
result

array([[ 33,  36,  39],
       [114, 126, 138],
       [195, 216, 237]])

In [95]:
common_ele = np.intersect1d(a,b)

In [96]:
common_ele

array([6, 7, 8])

In [97]:
matrix = np.arange(1,101).reshape(10,10)

In [98]:
matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [103]:
slice_matrix = matrix[3:6, 3:6]
slice_matrix.max()

np.int64(56)

In [104]:
arr = np.array([[10, 3],
                [5, 1],
                [8, 2]])

In [105]:
arr

array([[10,  3],
       [ 5,  1],
       [ 8,  2]])

In [107]:
shorted_arr = arr[arr[:, 1].argsort()]
shorted_arr

array([[ 5,  1],
       [ 8,  2],
       [10,  3]])

In [110]:
arr = np.array([[5, 12, 7],
                [3, 18, 1],
                [10, 6, 15]])
threshold = 10


In [111]:
arr

array([[ 5, 12,  7],
       [ 3, 18,  1],
       [10,  6, 15]])

In [113]:
mask = arr > threshold

In [114]:
mask

array([[False,  True, False],
       [False,  True, False],
       [False, False,  True]])

In [115]:
arr[mask]

array([12, 18, 15])